global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:

  - job_name: "rag-service"
    static_configs:
      - targets: ["rag-service:8001"]

  - job_name: "llm-service"
    static_configs:
      - targets: ["llm-service:8002"]

  - job_name: "memory-service"
    static_configs:
      - targets: ["memory-service:8003"]

  - job_name: "agent-service"
    static_configs:
      - targets: ["agent-service:8004"]

  - job_name: "gateway-service"
    static_configs:
      - targets: ["gateway-service:8000"]

  - job_name: "weather-agent"
    static_configs:
      - targets: ["weather-agent:8011"]

  - job_name: "search-agent"
    static_configs:
      - targets: ["search-agent:8012"]

  - job_name: 'blackbox-http'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - http://gateway-service:8000/health
        - http://llm-service:8002/health
        - http://rag-service:8001/health
        - http://memory-service:8003/health
        - http://agent-service:8004/health
        - http://weather-agent:8011/health
        - http://search-agent:8012/health
        - https://github.com    
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115
