# Service for Weather Service (HTTP & gRPC)
apiVersion: v1
kind: Service
metadata:
  name: weather-service-svc
  namespace: agentica-app
spec:
  selector:
    app: weather-service
  ports:
    - name: http-api
      protocol: TCP
      port: 8011 # Internal service port for HTTP
      targetPort: 8011 # Container's HTTP port
    # - name: grpc-api
    #   protocol: TCP
    #   port: 50052
    #   targetPort: 50052
  type: ClusterIP